<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\GoogleLanguageConstant;

class StoreGoogleLanguageConstantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        echo "Start Store Google Language Constant Seeder \n";
        GoogleLanguageConstant::truncate();

        $input = [
            [
                'google_language_constant_id' => 1000,
                'code' => 'en',
                'name' => 'English',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1001,
                'code' => 'de',
                'name' => 'German',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1002,
                'code' => 'fr',
                'name' => 'French',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1003,
                'code' => 'es',
                'name' => 'Spanish',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1004,
                'code' => 'it',
                'name' => 'Italian',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1005,
                'code' => 'ja',
                'name' => 'Japanese',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1006,
                'code' => 'en_US',
                'name' => 'English (US)',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1007,
                'code' => 'en_GB',
                'name' => 'English (UK)',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1008,
                'code' => 'zh',
                'name' => 'Chinese',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1009,
                'code' => 'da',
                'name' => 'Danish',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1010,
                'code' => 'nl',
                'name' => 'Dutch',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1011,
                'code' => 'fi',
                'name' => 'Finnish',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1012,
                'code' => 'ko',
                'name' => 'Korean',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1013,
                'code' => 'no',
                'name' => 'Norwegian',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1014,
                'code' => 'pt',
                'name' => 'Portuguese',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1015,
                'code' => 'sv',
                'name' => 'Swedish',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1016,
                'code' => 'pt_BR',
                'name' => 'Portuguese (Brazil)',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1017,
                'code' => 'zh_CN',
                'name' => 'Chinese (simplified)',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1018,
                'code' => 'zh_TW',
                'name' => 'Chinese (traditional)',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1019,
                'code' => 'ar',
                'name' => 'Arabic',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1020,
                'code' => 'bg',
                'name' => 'Bulgarian',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1021,
                'code' => 'cs',
                'name' => 'Czech',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1022,
                'code' => 'el',
                'name' => 'Greek',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1023,
                'code' => 'hi',
                'name' => 'Hindi',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1024,
                'code' => 'hu',
                'name' => 'Hungarian',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1025,
                'code' => 'id',
                'name' => 'Indonesian',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1026,
                'code' => 'is',
                'name' => 'Icelandic',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1027,
                'code' => 'iw',
                'name' => 'Hebrew',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1028,
                'code' => 'lv',
                'name' => 'Latvian',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1029,
                'code' => 'lt',
                'name' => 'Lithuanian',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1030,
                'code' => 'pl',
                'name' => 'Polish',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1031,
                'code' => 'ru',
                'name' => 'Russian',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1032,
                'code' => 'ro',
                'name' => 'Romanian',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1033,
                'code' => 'sk',
                'name' => 'Slovak',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1034,
                'code' => 'sl',
                'name' => 'Slovenian',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1035,
                'code' => 'sr',
                'name' => 'Serbian',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1036,
                'code' => 'uk',
                'name' => 'Ukrainian',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1037,
                'code' => 'tr',
                'name' => 'Turkish',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1038,
                'code' => 'ca',
                'name' => 'Catalan',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1039,
                'code' => 'hr',
                'name' => 'Croatian',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1040,
                'code' => 'vi',
                'name' => 'Vietnamese',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1041,
                'code' => 'ur',
                'name' => 'Urdu',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1042,
                'code' => 'tl',
                'name' => 'Filipino',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1043,
                'code' => 'et',
                'name' => 'Estonian',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1044,
                'code' => 'th',
                'name' => 'Thai',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1045,
                'code' => 'aa',
                'name' => 'Afar',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1046,
                'code' => 'ab',
                'name' => 'Abkhazian',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1047,
                'code' => 'af',
                'name' => 'Afrikaans',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1048,
                'code' => 'am',
                'name' => 'Amharic',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1049,
                'code' => 'as',
                'name' => 'Assamese',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1050,
                'code' => 'ay',
                'name' => 'Aymara',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1051,
                'code' => 'az',
                'name' => 'Azerbaijani',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1052,
                'code' => 'ba',
                'name' => 'Bashkir',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1053,
                'code' => 'be',
                'name' => 'Belarusian',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1054,
                'code' => 'bh',
                'name' => 'Bihari',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1055,
                'code' => 'bi',
                'name' => 'Bislama',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1056,
                'code' => 'bn',
                'name' => 'Bengali',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1057,
                'code' => 'bo',
                'name' => 'Tibetan',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1058,
                'code' => 'br',
                'name' => 'Breton',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1059,
                'code' => 'co',
                'name' => 'Corsican',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1060,
                'code' => 'cy',
                'name' => 'Welsh',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1061,
                'code' => 'nn',
                'name' => 'Norwegian Nynorsk',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1062,
                'code' => 'eo',
                'name' => 'Esperanto',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1063,
                'code' => 'eu',
                'name' => 'Basque',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1064,
                'code' => 'fa',
                'name' => 'Persian',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1065,
                'code' => 'fj',
                'name' => 'Fijian',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1066,
                'code' => 'fo',
                'name' => 'Faroese',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1067,
                'code' => 'fy',
                'name' => 'Western Frisian',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1068,
                'code' => 'ga',
                'name' => 'Irish',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1069,
                'code' => 'gd',
                'name' => 'Scottish Gaelic',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1070,
                'code' => 'gl',
                'name' => 'Galician',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1071,
                'code' => 'gn',
                'name' => 'Guarani',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1072,
                'code' => 'gu',
                'name' => 'Gujarati',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1073,
                'code' => 'gv',
                'name' => 'Manx',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1074,
                'code' => 'ha',
                'name' => 'Hausa',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1075,
                'code' => 'bs',
                'name' => 'Bosnian',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1076,
                'code' => 'hy',
                'name' => 'Armenian',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1077,
                'code' => 'ia',
                'name' => 'Interlingua',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1078,
                'code' => 'ie',
                'name' => 'Interlingue',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1079,
                'code' => 'ik',
                'name' => 'Inupiaq',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1080,
                'code' => 'iu',
                'name' => 'Inuktitut',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1081,
                'code' => 'jv',
                'name' => 'Javanese',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1082,
                'code' => 'ka',
                'name' => 'Georgian',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1083,
                'code' => 'kk',
                'name' => 'Kazakh',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1084,
                'code' => 'kl',
                'name' => 'Greenlandic',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1085,
                'code' => 'km',
                'name' => 'Khmer',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1086,
                'code' => 'kn',
                'name' => 'Kannada',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1087,
                'code' => 'ks',
                'name' => 'Kashmiri',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1088,
                'code' => 'ku',
                'name' => 'Kurdish',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1089,
                'code' => 'kw',
                'name' => 'Cornish',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1090,
                'code' => 'ky',
                'name' => 'Kirghiz',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1091,
                'code' => 'la',
                'name' => 'Latin',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1092,
                'code' => 'lb',
                'name' => 'Luxembourgish',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1093,
                'code' => 'ln',
                'name' => 'Lingala',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1094,
                'code' => 'lo',
                'name' => 'Lao',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1095,
                'code' => 'mg',
                'name' => 'Malagasy',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1096,
                'code' => 'mi',
                'name' => 'Maori',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1097,
                'code' => 'mk',
                'name' => 'Macedonian',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1098,
                'code' => 'ml',
                'name' => 'Malayalam',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1099,
                'code' => 'mn',
                'name' => 'Mongolian',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1100,
                'code' => 'mo',
                'name' => 'Moldavian',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1101,
                'code' => 'mr',
                'name' => 'Marathi',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1102,
                'code' => 'ms',
                'name' => 'Malay',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1103,
                'code' => 'mt',
                'name' => 'Maltese',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1104,
                'code' => 'my',
                'name' => 'Burmese',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1105,
                'code' => 'na',
                'name' => 'Nauru',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1106,
                'code' => 'ne',
                'name' => 'Nepali',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1107,
                'code' => 'oc',
                'name' => 'Occitan',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1108,
                'code' => 'om',
                'name' => '(Afan) Oromo',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1109,
                'code' => 'or',
                'name' => 'Oriya',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1110,
                'code' => 'pa',
                'name' => 'Punjabi',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1111,
                'code' => 'ps',
                'name' => 'Pushto',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1112,
                'code' => 'qu',
                'name' => 'Quechua',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1113,
                'code' => 'rm',
                'name' => 'Raeto-Romance',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1114,
                'code' => 'rn',
                'name' => 'Rundi',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1115,
                'code' => 'rw',
                'name' => 'Kinyarwanda',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1116,
                'code' => 'sa',
                'name' => 'Sanskrit',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1117,
                'code' => 'sd',
                'name' => 'Sindhi',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1118,
                'code' => 'se',
                'name' => 'Northern S�mi',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1119,
                'code' => 'sg',
                'name' => 'Sango',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1120,
                'code' => 'zu',
                'name' => 'Zulu',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1121,
                'code' => 'si',
                'name' => 'Sinhalese',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1122,
                'code' => 'sm',
                'name' => 'Samoan',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1123,
                'code' => 'sn',
                'name' => 'Shona',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1124,
                'code' => 'so',
                'name' => 'Somali',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1125,
                'code' => 'sq',
                'name' => 'Albanian',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1126,
                'code' => 'ss',
                'name' => 'Swati',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1127,
                'code' => 'st',
                'name' => 'Sotho',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1128,
                'code' => 'su',
                'name' => 'Sundanese',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1129,
                'code' => 'sw',
                'name' => 'Swahili',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1130,
                'code' => 'ta',
                'name' => 'Tamil',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1131,
                'code' => 'te',
                'name' => 'Telugu',
                'is_targetable' => true,
            ],
            [
                'google_language_constant_id' => 1132,
                'code' => 'tg',
                'name' => 'Tajik',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1133,
                'code' => 'ti',
                'name' => 'Tigrinya',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1134,
                'code' => 'tk',
                'name' => 'Turkmen',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1135,
                'code' => 'tn',
                'name' => 'Tswana',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1136,
                'code' => 'to',
                'name' => 'Tonga',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1137,
                'code' => 'ts',
                'name' => 'Tsonga',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1138,
                'code' => 'tt',
                'name' => 'Tatar',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1139,
                'code' => 'tw',
                'name' => 'Twi',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1140,
                'code' => 'ug',
                'name' => 'Uighur',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1141,
                'code' => 'uz',
                'name' => 'Uzbek',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1142,
                'code' => 'vo',
                'name' => 'Volap�k',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1143,
                'code' => 'wo',
                'name' => 'Wolof',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1144,
                'code' => 'xh',
                'name' => 'Xhosa',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1145,
                'code' => 'yi',
                'name' => 'Yiddish',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1146,
                'code' => 'yo',
                'name' => 'Yoruba',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1147,
                'code' => 'za',
                'name' => 'Zhuang',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1148,
                'code' => 'en_AU',
                'name' => 'English (Australia)',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1149,
                'code' => 'pt_PT',
                'name' => 'Portuguese (Portugal)',
                'is_targetable' => false,
            ],
            [
                'google_language_constant_id' => 1150,
                'code' => 'zh_HK',
                'name' => 'Chinese (Hong Kong SAR)',
                'is_targetable' => false,
            ],
        ];

        GoogleLanguageConstant::insert($input);
        echo "End Store Google Language Constant Seeder \n";
    }
}
