version: "3"
services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - erp
  erp-web:
    image: nginx:alpine
    container_name: erp-web
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    depends_on:
      - erp-app
    networks:
      - erp

  erp-app:
    image: luxury123456/erp-app
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: erp-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    #network_mode: host
    command:
      - /bin/sh
      - -c
      - |
        php-fpm &
        cd /var/www/ && php artisan horizon &
        wait
    env_file:
      - ".env"
        #        command: bash -c "composer config -g github-oauth.github.com ${GITHUB_TOKEN}"
    networks:
      - erp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: pma
    environment:
      PMA_HOST: erp-prod.cv6cock2mhwb.us-east-2.rds.amazonaws.com
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8098:80

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/default.conf
volumes:
  dbdata:
networks:
  erp:
    driver: bridge
