-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgidw4QGrkzW9jhQK4
NgZnRQ2bTjEtxGBdQUtycS6JitygCgYIKoZIzj0DAQehRANCAASvmdxFaMnJ1SYG
J/TAQdVWIAu2bhlNUUKVK/a1o8/q+9wYB2k+z/1zEuZiG+9/YcoEiJSS3r/GHjWJ
Zf5PMmKA
-----END PRIVATE KEY-----